defmodule HerrFreud.Memory.StoreTest do
  use ExUnit.Case, async: true
  alias HerrFreud.Memory.Store
  alias HerrFreud.Memory.Session
  alias HerrFreud.Memory.Memory
  alias HerrFreud.Repo
  import Ecto.Query

  # Minimal valid session attrs — only embedding is optional for sessions
  defp session_attrs(id \\ "session-#{:rand.uniform(999_999)}") do
    %{
      id: id,
      date: Date.utc_today(),
      input_mode: "text",
      source_lang: "en",
      english_transcript: "Transcript",
      response: "Response",
      style_used: "single_question",
      embedding: nil
    }
  end

  # Memory attrs require a valid session_id and embedding (NOT NULL).
  # When inserted_at is provided it overrides the autogenerated timestamp.
  defp memory_attrs(session_id, extra) do
    Map.merge(
      %{
        session_id: session_id,
        content: "Memory content",
        embedding: <<0>>
      },
      extra
    )
  end

  # Past DateTime for testing delete_memories_older_than cutoff logic
  defp days_ago(days) do
    DateTime.add(DateTime.utc_now(), -days * 86400, :second) |> DateTime.truncate(:second)
  end

  setup do
    Repo.delete_all(from s in Session)
    Repo.delete_all(from m in Memory)
    :ok
  end

  # ---------------------------------------------------------------------------
  # Sessions
  # ---------------------------------------------------------------------------

  describe "insert_session/1" do
    test "inserts a session with all fields" do
      attrs = %{
        id: "test-session-#{:rand.uniform(999_999)}",
        date: Date.utc_today(),
        input_mode: "text",
        source_lang: "en",
        raw_transcript: "Hello, I had a difficult day.",
        english_transcript: "Hello, I had a difficult day.",
        response: "Thank you for sharing.",
        style_used: "single_question",
        embedding: nil
      }

      assert {:ok, session} = Store.insert_session(attrs)
      assert session.id == attrs.id
      assert session.input_mode == "text"
      assert session.source_lang == "en"
      assert session.raw_transcript == "Hello, I had a difficult day."
      assert session.english_transcript == "Hello, I had a difficult day."
      assert session.response == "Thank you for sharing."
      assert session.style_used == "single_question"
      assert session.inserted_at != nil
    end

    test "generates ID if not provided" do
      attrs = %{
        date: Date.utc_today(),
        input_mode: "voice",
        source_lang: "de",
        english_transcript: "Generiert",
        response: "Antwort",
        style_used: "single_question",
        embedding: nil
      }

      assert {:ok, session} = Store.insert_session(attrs)
      assert session.id != nil
    end

    test "defaults date to today when not provided" do
      attrs = %{
        id: "test-session-#{:rand.uniform(999_999)}",
        input_mode: "text",
        source_lang: "en",
        english_transcript: "Hello",
        response: "Hi",
        style_used: "single_question",
        embedding: nil
      }

      assert {:ok, session} = Store.insert_session(attrs)
      assert session.date == Date.utc_today()
    end

    test "generates inserted_at timestamp" do
      attrs = %{
        id: "test-session-#{:rand.uniform(999_999)}",
        date: Date.utc_today(),
        input_mode: "text",
        source_lang: "en",
        english_transcript: "Hello",
        response: "Hi",
        style_used: "single_question",
        embedding: nil
      }

      assert {:ok, session} = Store.insert_session(attrs)
      assert session.inserted_at != nil
    end
  end

  describe "get_session/1" do
    test "returns session when it exists" do
      {:ok, inserted} = Store.insert_session(session_attrs())

      session = Store.get_session(inserted.id)
      assert session != nil
      assert session.id == inserted.id
      assert session.input_mode == "text"
    end

    test "returns nil when session does not exist" do
      assert Store.get_session("nonexistent-id") == nil
    end
  end

  describe "list_sessions/0" do
    test "returns empty list when no sessions exist" do
      assert Store.list_sessions() == []
    end

    test "returns all sessions ordered by most recent first" do
      s1_id = "test-session-a-#{:rand.uniform(999_999)}"
      s2_id = "test-session-b-#{:rand.uniform(999_999)}"
      s3_id = "test-session-c-#{:rand.uniform(999_999)}"

      Store.insert_session(%{session_attrs(s1_id) | date: ~D[2024-01-01], english_transcript: "One"})
      Process.sleep(10)
      Store.insert_session(%{session_attrs(s2_id) | date: ~D[2024-01-02], english_transcript: "Two"})
      Process.sleep(10)
      Store.insert_session(%{session_attrs(s3_id) | date: ~D[2024-01-03], english_transcript: "Three"})

      sessions = Store.list_sessions()
      ids = Enum.map(sessions, & &1.id)

      assert length(sessions) == 3
      assert ids == [s3_id, s2_id, s1_id]
    end
  end

  describe "list_sessions_since/1" do
    test "with a date — returns sessions on or after the given date" do
      Store.insert_session(%{session_attrs("old-#{:rand.uniform(999_999)}") | date: ~D[2024-01-01], english_transcript: "Old"})
      Store.insert_session(%{session_attrs("mid-#{:rand.uniform(999_999)}") | date: ~D[2024-01-15], english_transcript: "Mid"})
      Store.insert_session(%{session_attrs("new-#{:rand.uniform(999_999)}") | date: ~D[2024-02-01], english_transcript: "New"})

      sessions = Store.list_sessions_since(~D[2024-01-15])

      assert length(sessions) == 2
      dates = Enum.map(sessions, & &1.date)
      refute ~D[2024-01-01] in dates
    end

    test "with an ISO8601 binary date — parses and filters correctly" do
      Store.insert_session(%{session_attrs("old2-#{:rand.uniform(999_999)}") | date: ~D[2024-01-01], english_transcript: "Old"})
      Store.insert_session(%{session_attrs("new2-#{:rand.uniform(999_999)}") | date: ~D[2024-03-01], english_transcript: "New"})

      sessions = Store.list_sessions_since("2024-02-01")

      assert length(sessions) == 1
      assert hd(sessions).date == ~D[2024-03-01]
    end

    test "with a date in the future — returns empty list" do
      Store.insert_session(session_attrs("future-#{:rand.uniform(999_999)}"))

      sessions = Store.list_sessions_since(Date.add(Date.utc_today(), 30))

      assert sessions == []
    end
  end

  describe "get_most_recent_session/0" do
    test "returns nil when no sessions exist" do
      assert Store.get_most_recent_session() == nil
    end

    test "returns the most recently inserted session" do
      s1_id = "first-#{:rand.uniform(999_999)}"
      s2_id = "last-#{:rand.uniform(999_999)}"

      Store.insert_session(%{session_attrs(s1_id) | date: ~D[2024-01-01], english_transcript: "First"})
      Process.sleep(10)
      Store.insert_session(%{session_attrs(s2_id) | date: ~D[2024-01-02], english_transcript: "Last"})

      assert Store.get_most_recent_session().id == s2_id
    end
  end

  # ---------------------------------------------------------------------------
  # Memories
  # ---------------------------------------------------------------------------

  describe "insert_memory/1" do
    test "inserts a memory with all fields" do
      {:ok, session} = Store.insert_session(session_attrs())

      attrs = memory_attrs(session.id, %{
        id: "test-memory-#{:rand.uniform(999_999)}",
        content: "Patient mentioned recurring dreams.",
        recency_score: 0.9
      })

      assert {:ok, memory} = Store.insert_memory(attrs)
      assert memory.id == attrs.id
      assert memory.session_id == session.id
      assert memory.content == "Patient mentioned recurring dreams."
      assert memory.recency_score == 0.9
      assert memory.inserted_at != nil
    end

    test "defaults recency_score to 1.0 when not provided" do
      {:ok, session} = Store.insert_session(session_attrs())

      {:ok, memory} = Store.insert_memory(memory_attrs(session.id, %{recency_score: nil}))

      assert memory.recency_score == 1.0
    end

    test "generates ID if not provided" do
      {:ok, session} = Store.insert_session(session_attrs())

      {:ok, memory} = Store.insert_memory(memory_attrs(session.id, %{id: nil}))

      assert memory.id != nil
    end
  end

  describe "get_memories_for_session/1" do
    test "returns empty list when session has no memories" do
      {:ok, session} = Store.insert_session(session_attrs())
      assert Store.get_memories_for_session(session.id) == []
    end

    test "returns memories belonging to the given session only" do
      {:ok, session} = Store.insert_session(session_attrs())
      {:ok, other} = Store.insert_session(session_attrs("other-#{:rand.uniform(999_999)}"))

      {:ok, _m1} = Store.insert_memory(memory_attrs(session.id, %{content: "Target session memory 1", id: nil}))
      {:ok, _m2} = Store.insert_memory(memory_attrs(session.id, %{content: "Target session memory 2", id: nil}))
      {:ok, _m3} = Store.insert_memory(memory_attrs(other.id, %{content: "Other session memory", id: nil}))

      memories = Store.get_memories_for_session(session.id)

      assert length(memories) == 2
      contents = Enum.map(memories, & &1.content)
      assert "Target session memory 1" in contents
      assert "Target session memory 2" in contents
      refute "Other session memory" in contents
    end
  end

  describe "list_memories/0" do
    test "returns empty list when no memories exist" do
      assert Store.list_memories() == []
    end

    test "returns all memories regardless of session" do
      {:ok, s1} = Store.insert_session(session_attrs())
      {:ok, s2} = Store.insert_session(session_attrs())

      Store.insert_memory(memory_attrs(s1.id, %{content: "From session 1", id: nil}))
      Store.insert_memory(memory_attrs(s2.id, %{content: "From session 2", id: nil}))

      assert length(Store.list_memories()) == 2
    end
  end

  describe "delete_memories_older_than/2" do
    test "with a date — deletes nothing when no memories are older than cutoff" do
      {:ok, s1} = Store.insert_session(session_attrs())
      {:ok, s2} = Store.insert_session(session_attrs())

      # Both inserted with future-dated inserted_at (beyond cutoff)
      future = DateTime.add(DateTime.utc_now(), 60 * 86400, :second) |> DateTime.truncate(:second)
      Store.insert_memory(memory_attrs(s1.id, %{content: "Old memory", id: nil, inserted_at: future}))
      Store.insert_memory(memory_attrs(s2.id, %{content: "New memory", id: nil, inserted_at: future}))

      cutoff = Date.add(Date.utc_today(), 30)
      {count, nil} = Store.delete_memories_older_than(cutoff)
      assert count == 0
      assert length(Store.list_memories()) == 2
    end

    test "with a date — deletes all when all memories are older than cutoff" do
      {:ok, s1} = Store.insert_session(session_attrs())
      {:ok, s2} = Store.insert_session(session_attrs())

      past = days_ago(10)
      Store.insert_memory(memory_attrs(s1.id, %{content: "Memory 1", id: nil, inserted_at: past}))
      Store.insert_memory(memory_attrs(s2.id, %{content: "Memory 2", id: nil, inserted_at: past}))

      past_cutoff = Date.add(Date.utc_today(), -1)
      {count, nil} = Store.delete_memories_older_than(past_cutoff)
      assert count == 2
      assert Store.list_memories() == []
    end

    test "with a date — deletes only memories older than cutoff" do
      {:ok, s1} = Store.insert_session(session_attrs())
      {:ok, s2} = Store.insert_session(session_attrs())

      Store.insert_memory(memory_attrs(s1.id, %{content: "Old memory", id: nil, inserted_at: days_ago(10)}))
      Store.insert_memory(memory_attrs(s2.id, %{content: "Recent memory", id: nil, inserted_at: days_ago(1)}))

      cutoff = Date.add(Date.utc_today(), -5)
      {count, nil} = Store.delete_memories_older_than(cutoff)
      assert count == 1
      remaining = Store.list_memories()
      assert length(remaining) == 1
      assert hd(remaining).content == "Recent memory"
    end

    test "with an ISO8601 binary date — parses and deletes correctly" do
      {:ok, session} = Store.insert_session(session_attrs())
      {:ok, _} = Store.insert_memory(memory_attrs(session.id, %{content: "Old", id: nil, inserted_at: days_ago(10)}))

      # Binary is parsed, old memory deleted, recent memory kept
      {:ok, _recent} = Store.insert_memory(memory_attrs(session.id, %{content: "Recent", id: nil}))
      past_date = Date.add(Date.utc_today(), -5) |> Date.to_iso8601()
      {count, nil} = Store.delete_memories_older_than(past_date)
      assert count == 1
      remaining = Store.list_memories()
      assert length(remaining) == 1
      assert hd(remaining).content == "Recent"
    end

    test "returns {0, nil} when no memories match the cutoff" do
      {:ok, session} = Store.insert_session(session_attrs())
      future = DateTime.add(DateTime.utc_now(), 60 * 86400, :second) |> DateTime.truncate(:second)
      Store.insert_memory(memory_attrs(session.id, %{content: "Memory", id: nil, inserted_at: future}))

      future_date = Date.add(Date.utc_today(), 30) |> Date.to_iso8601()
      {count, nil} = Store.delete_memories_older_than(future_date)
      assert count == 0
    end
  end

  describe "update_recency_score/2" do
    test "updates the recency score of an existing memory" do
      {:ok, session} = Store.insert_session(session_attrs())
      {:ok, memory} = Store.insert_memory(memory_attrs(session.id, %{recency_score: 1.0}))

      assert {:ok, updated} = Store.update_recency_score(memory.id, 0.5)
      assert updated.id == memory.id
      assert updated.recency_score == 0.5
    end

    test "raises FunctionClauseError when memory does not exist" do
      assert_raise FunctionClauseError, fn ->
        Store.update_recency_score("nonexistent-id", 0.5)
      end
    end
  end
end
